name: deploy-container

on:
 push:
  branches:
   - main
  paths:
   - 'container/**'

defaults:
 run:
  working-directory: 'container'

jobs: 
 build:
  runs-on: ubuntu-latest

  - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

  steps:
  - uses: actions/checkout@v2
  - run: npm install
  - run: npm run build
